name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    strategy:
      matrix:
        llvm:
        - {id: llvm-9, version: '9.0'}
        - {id: llvm-10, version: '10.0'}
        config:
        - {cc: gcc-8, cxx: g++-8}
        - {cc: gcc-9, cxx: g++-9}
        - {cc: gcc-10, cxx: g++-10}

    steps:
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: ${{runner.temp}}/llvm
        key: ${{matrix.llvm.id}}

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{matrix.llvm.version}}
        directory: ${{runner.temp}}/llvm
        cached: ${{steps.cache-llvm.outputs.cache-hit}}

    - name: Checkout YuLang
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      env:
        CC: ${{matrix.config.cc}}
        CXX: ${{matrix.config.cxx}}
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -j8

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: $GITHUB_WORKSPACE/utils/run_test.sh ${{runner.workspace}}/build
